version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: src/mrnntorch/docs/conf.py

formats:
  - htmlzip

python:
  install:
    - requirements: src/mrnntorch/docs/requirements.txt
